version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/rbnd
          - DOCKER_BUILDKIT=1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build --progress plain -t minid:latest -f Dockerfile.minid .
      - run: |
          TAG_NAME=$(date -u '+%Y%m%d%H%M%S')
          echo "${REPO_NAME}:${TAG_NAME}"
          cat Dockerfile | docker run -i --rm minid:latest minid -f - | docker build --progress plain --build-arg APT_MIRROR=US -t "${REPO_NAME}:${TAG_NAME}" -f - .
      - deploy:
          command: |
            docker images "${REPO_NAME}"
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              for TAG_NAME in $(docker images "${REPO_NAME}" --format "{{.Tag}}"); do
                docker push "${REPO_NAME}:${TAG_NAME}"
              done
            fi
