version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/rbnd
          - DOCKER_BUILDKIT=1
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          docker build --progress plain -t minid:latest -f Dockerfile.minid .
      - run: |
          date -u '+%Y%m%d%H%M%S' > TAG_NAME
          echo "TAG_NAME=$(cat TAG_NAME)"
      - run: |
          TAG_NAME=$(cat TAG_NAME)
          cat Dockerfile | docker run -i --rm minid:latest minid -f - | docker build --squash --progress plain --build-arg APT_MIRROR=US -t "${REPO_NAME}:${TAG_NAME}" -f - .
      - deploy:
          command: |
            docker images "${REPO_NAME}"
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              TAG_NAME=$(cat TAG_NAME)
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push "${REPO_NAME}:${TAG_NAME}"
            fi
